author: "Jonhnny Weslley"
description: "Procker is a tool for managing Procfile-based applications."
filesets:
  includes:
  - README.md
  - LICENSE
  excludes:
  - \.git
  - .*\.go
  depth: 3
settings:
  targetdir: 'bin'
  outfiles: ['bin/procker']
  build: go install -v ./...
